theme: jekyll-theme-minimal
title: Swati
description: [Researcher,<br/>
Artificial Intelligence Laboratory,<br/>Jo≈æef Stefan Institute,<br/>Ljubljana]
show_downloads: false
logo: /assets/img/pic.jpeg
github:
  is_project_page: false
